In [1]:
import pandas as pd
alunos = { 'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4, 7, 5.5, 9],
          'Aprovado': ['Não', 'Sim', 'Não', 'Sim']
          
    
}

print(alunos)

{'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 'Nota': [4, 7, 5.5, 9], 'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}


In [2]:
dataframe = pd.DataFrame(alunos)

In [4]:
display(dataframe)

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [5]:
#series = cria um array com indices.
objeto1 = pd.Series([2,6,9,10,5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [9]:
import numpy as np

array1 = np.array([2,6,9,10,5])
array2 = np.array([(2,6,9,10,5), (6, 12, 2, 9, 10)])                  

print(array1)
print(array2)

[ 2  6  9 10  5]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [10]:
objeto2 = pd.Series(array1)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32
